import os
import argparse
import numpy as np
import pandas as pd

# =========================================================
# paths
# =========================================================
SPLIT_OUTPUT_BASE_DIR = "../../../data/2_tree_construction/2_1_split/2_1_3_split_impute/output"
COMBINE_OUTPUT_BASE_DIR = "../../../data/2_tree_construction/2_2_combine_portfolio/2_2_3_combine_impute/output"
RF_PATH = "../../../data/common/rf.csv"

# fixed columns
DATE_COL = "date"


def list_year_dirs(input_dir: str):
    year_dirs = []
    for name in os.listdir(input_dir):
        full_path = os.path.join(input_dir, name)
        if os.path.isdir(full_path) and name.isdigit():
            year_dirs.append(int(name))
    return sorted(year_dirs)


def load_combo_specs(input_dir: str):
    path = os.path.join(input_dir, "combo_specs.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Cannot find combo specs file: {path}")
    return pd.read_csv(path)


def load_tree_specs(input_dir: str):
    path = os.path.join(input_dir, "tree_specs.csv")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Cannot find tree specs file: {path}")
    return pd.read_csv(
        path,
        dtype={
            "tree_id": str,
            "sequence_digits": str,
            "sequence_idx": str
        }
    )


def load_metadata(input_dir: str):
    path = os.path.join(input_dir, "metadata.parquet")
    if not os.path.exists(path):
        raise FileNotFoundError(f"Cannot find metadata file: {path}")
    return pd.read_parquet(path)


def load_yearly_return_long(file_path: str):
    """
    Read one year's split-level long return file:
        columns: date, combo_id, tree_id, node_id, column_name, ret
    """
    if not os.path.exists(file_path):
        return None

    df = pd.read_parquet(file_path).copy()
    if df.empty:
        return None

    required_cols = ["date", "combo_id", "tree_id", "node_id", "column_name", "ret"]
    missing = [c for c in required_cols if c not in df.columns]
    if len(missing) > 0:
        raise ValueError(f"Missing required columns {missing} in {file_path}")

    df[DATE_COL] = pd.to_datetime(df[DATE_COL])

    # safety check: one row per (date, combo_id, tree_id, node_id)
    dup_n = df.duplicated(subset=[DATE_COL, "combo_id", "tree_id", "node_id"]).sum()
    if dup_n > 0:
        raise ValueError(
            f"Duplicate (date, combo_id, tree_id, node_id) rows found in {file_path}: {dup_n}"
        )

    # keep only needed columns for combine
    return df[[DATE_COL, "column_name", "ret"]]


def concat_yearly_long_returns(file_paths):
    dfs = []

    for fp in file_paths:
        df = load_yearly_return_long(fp)
        if df is None:
            continue
        dfs.append(df)

    if len(dfs) == 0:
        return None

    out = pd.concat(dfs, axis=0, ignore_index=True)
    out = out.sort_values([DATE_COL, "column_name"]).reset_index(drop=True)

    dup_n = out.duplicated(subset=[DATE_COL, "column_name"]).sum()
    if dup_n > 0:
        raise ValueError(f"Duplicate (date, column_name) rows found after concat: {dup_n}")

    return out


def pivot_return_long_to_wide(df_long: pd.DataFrame):
    """
    Convert long-form split return table to wide portfolio matrix.
    index   = date
    columns = column_name
    values  = ret
    """
    wide = df_long.pivot(index=DATE_COL, columns="column_name", values="ret")
    wide = wide.sort_index().reset_index()

    # remove columns.name generated by pivot
    wide.columns.name = None
    return wide


def convert_tb3ms_to_monthly_rf(rf_df: pd.DataFrame):
    rf_df = rf_df.copy()
    rf_df["observation_date"] = pd.to_datetime(rf_df["observation_date"])
    rf_df["month"] = rf_df["observation_date"].dt.to_period("M")
    rf_df["rf_monthly"] = (1.0 + rf_df["TB3MS"] / 100.0) ** (1.0 / 12.0) - 1.0
    rf_df = rf_df[["month", "rf_monthly"]].drop_duplicates(subset=["month"]).sort_values("month")
    return rf_df


def subtract_rf(ret_df: pd.DataFrame, rf_path: str):
    ret_df = ret_df.copy()
    ret_df[DATE_COL] = pd.to_datetime(ret_df[DATE_COL])
    ret_df["month"] = ret_df[DATE_COL].dt.to_period("M")

    rf_raw = pd.read_csv(rf_path)
    rf_monthly = convert_tb3ms_to_monthly_rf(rf_raw)

    ret_df = ret_df.merge(rf_monthly, on="month", how="left")

    ret_cols = [c for c in ret_df.columns if c not in [DATE_COL, "month", "rf_monthly"]]
    ret_df[ret_cols] = ret_df[ret_cols].sub(ret_df["rf_monthly"], axis=0)

    ret_df = ret_df.drop(columns=["month", "rf_monthly"])
    return ret_df


def dedup_columns_by_values(df: pd.DataFrame):
    non_date_cols = [c for c in df.columns if c != DATE_COL]

    if len(non_date_cols) == 0:
        return df[[DATE_COL]].copy(), []

    tmp = df[non_date_cols].T
    keep_mask = ~tmp.duplicated()

    keep_cols = list(tmp.index[keep_mask])
    out = df[[DATE_COL] + keep_cols].copy()

    return out, keep_cols


def drop_zero_variance_columns(df: pd.DataFrame):
    """
    Keep a column if:
    - it has at least 2 finite observations
    - and std over the finite part is positive
    """
    non_date_cols = [c for c in df.columns if c != DATE_COL]

    keep_cols = []
    for c in non_date_cols:
        x = df[c].to_numpy(dtype=float)
        good = np.isfinite(x)

        if good.sum() < 2:
            continue

        if np.std(x[good], ddof=0) > 0:
            keep_cols.append(c)

    out = df[[DATE_COL] + keep_cols].copy()
    return out, keep_cols


def make_repeat_tag(repeat_idx: int, seed: int, B: int, depth: int):
    return f"repeat_{repeat_idx:02d}_seed_{seed}_B_{B}_depth_{depth}"


def combine_one_repeat(split_input_dir: str, output_dir: str, drop_missing_months: bool):
    if not os.path.exists(split_input_dir):
        raise FileNotFoundError(f"Cannot find split output dir: {split_input_dir}")

    os.makedirs(output_dir, exist_ok=True)

    combo_specs = load_combo_specs(split_input_dir)
    tree_specs = load_tree_specs(split_input_dir)
    metadata = load_metadata(split_input_dir)
    years = list_year_dirs(split_input_dir)

    if len(years) == 0:
        raise ValueError(f"No year folders found in {split_input_dir}")

    print(f"[INFO] Split input dir: {split_input_dir}")
    print(f"[INFO] Output dir: {output_dir}")
    print(f"[INFO] Years found: {years[0]} - {years[-1]}")
    print(f"[INFO] Number of combos: {len(combo_specs)}")
    print(f"[INFO] Number of valid trees per combo: {len(tree_specs)}")
    print(f"[INFO] Metadata shape before combine: {metadata.shape}")

    file_paths = [
        os.path.join(split_input_dir, str(year), "tree_node_returns.parquet")
        for year in years
    ]

    ret_long_all = concat_yearly_long_returns(file_paths)

    if ret_long_all is None:
        raise ValueError("No yearly tree_node_returns.parquet files found")

    print(f"[INFO] Long return rows loaded: {len(ret_long_all)}")

    combined_ret = pivot_return_long_to_wide(ret_long_all)
    print(f"[INFO] Combined shape before rf: {combined_ret.shape}")

    combined_excess = subtract_rf(combined_ret, RF_PATH)
    print(f"[INFO] Combined shape after rf: {combined_excess.shape}")

    if drop_missing_months:
        before_n = combined_excess.shape[0]
        combined_excess = combined_excess.dropna(axis=0, how="any").reset_index(drop=True)
        after_n = combined_excess.shape[0]
        print(f"[INFO] Dropped months with missing: {before_n - after_n}")

    before_cols = combined_excess.shape[1]
    combined_excess, _ = drop_zero_variance_columns(combined_excess)
    after_cols = combined_excess.shape[1]
    print(f"[INFO] Dropped zero variance columns: {before_cols - after_cols}")

    if combined_excess.shape[1] <= 1:
        raise ValueError(
            f"No portfolio columns survived zero-variance filtering in {split_input_dir}. "
            f"Only date column remains."
        )

    before_cols = combined_excess.shape[1]
    combined_excess, keep_cols = dedup_columns_by_values(combined_excess)
    after_cols = combined_excess.shape[1]
    print(f"[INFO] Dropped duplicated columns: {before_cols - after_cols}")

    # sync metadata to surviving columns
    keep_col_set = set(keep_cols)
    metadata_filtered = metadata[metadata["column_name"].isin(keep_col_set)].copy()

    metadata_filtered["column_name"] = pd.Categorical(
        metadata_filtered["column_name"],
        categories=keep_cols,
        ordered=True
    )
    metadata_filtered = metadata_filtered.sort_values("column_name").reset_index(drop=True)
    metadata_filtered["column_name"] = metadata_filtered["column_name"].astype(str)

    # final alignment check
    if list(combined_excess.columns[1:]) != metadata_filtered["column_name"].tolist():
        raise ValueError("Combined return columns and metadata are not aligned.")

    combined_excess.to_pickle(os.path.join(output_dir, "level_all_excess_ret_combined.pkl.gz"))
    combined_excess.to_csv(os.path.join(output_dir, "level_all_excess_ret_combined.csv"), index=False)
    metadata_filtered.to_csv(os.path.join(output_dir, "portfolio_metadata.csv"), index=False)

    print(f"[INFO] Final combined shape: {combined_excess.shape}")
    print(f"[INFO] Metadata shape: {metadata_filtered.shape}")
    print("[INFO] Combine step finished successfully")


def main(args):
    B = args.B
    depth = args.depth
    N = args.N
    base_seed = args.base_seed
    drop_missing_months = args.drop_missing_months

    if N <= 0:
        raise ValueError("N must be positive.")

    for repeat_idx in range(1, N + 1):
        seed = base_seed + repeat_idx - 1
        repeat_tag = make_repeat_tag(repeat_idx, seed, B, depth)

        split_input_dir = os.path.join(SPLIT_OUTPUT_BASE_DIR, repeat_tag)
        output_dir = os.path.join(COMBINE_OUTPUT_BASE_DIR, repeat_tag)

        print("=" * 80)
        print(f"[INFO] Combining repeat {repeat_idx}/{N}")
        print(f"[INFO] Seed used: {seed}")

        combine_one_repeat(
            split_input_dir=split_input_dir,
            output_dir=output_dir,
            drop_missing_months=drop_missing_months
        )

    print("=" * 80)
    print("[INFO] All repeats finished successfully")


if __name__ == "__main__":
    parser = argparse.ArgumentParser()

    parser.add_argument("--B", type=int, default=10)
    parser.add_argument("--depth", type=int, default=4)

    # N = how many independent repeats were generated in split
    parser.add_argument("--N", type=int, required=True)

    # seed for repeat r is base_seed + r - 1
    parser.add_argument("--base_seed", type=int, default=0)

    parser.add_argument("--drop_missing_months", action="store_true")

    args = parser.parse_args()
    main(args)